command:
  drupal:
    options:
      root: ${drupal.root}
      base-url: ${drupal.base_url}
    site-install:
      options:
        site-name: ${drupal.site.name}
        site-mail: ${drupal.site.mail}
        site-profile: ${drupal.site.profile}
        site-update: ${drupal.site.update}
        site-locale: ${drupal.site.locale}
        account-name: ${drupal.account.name}
        account-password: ${drupal.account.password}
        account-mail: ${drupal.account.mail}
        database-type: ${drupal.database.type}
        database-host: ${drupal.database.host}
        database-port: ${drupal.database.port}
        database-name: ${drupal.database.name}
        database-user: ${drupal.database.user}
        database-password: ${drupal.database.password}
        sites-subdir: ${drupal.site.sites_subdir}
    drush-setup:
      options:
        config-dir: ${drupal.root}/drush