command:
  drupal:
    options:
      root: ${drupal.root}
      base-url: ${drupal.base_url}
    site-install:
      options:
        site-name: ${drupal.site.name}
        site-mail: ${drupal.site.mail}
        site-profile: ${drupal.site.profile}
        site-update: ${drupal.site.update}
        site-locale: ${drupal.site.locale}
        account-name: ${drupal.account.name}
        account-password: ${drupal.account.password}
        account-mail: ${drupal.account.mail}
        # @deprecated
        # The "database-type" option will be removed in version 1.0.0. Use "database-scheme".
        database-type: ${drupal.database.type}
        database-scheme: ${drupal.database.scheme}
        database-host: ${drupal.database.host}
        database-port: ${drupal.database.port}
        database-name: ${drupal.database.name}
        database-user: ${drupal.database.user}
        database-password: ${drupal.database.password}
        sites-subdir: ${drupal.site.sites_subdir}
        config-dir: ${drupal.site.config_dir}
        skip-permissions-setup: ${drupal.site.skip_permissions_setup}
    drush-setup:
      options:
        config-dir: ${drupal.root}/drush
    settings-setup:
      options:
        sites-subdir: ${drupal.site.sites_subdir}
        settings-override-file: ${drupal.site.settings_override_file}
        force: ${drupal.site.force}
        skip-permissions-setup: ${drupal.site.skip_permissions_setup}
    permissions-setup:
      options:
        sites-subdir: ${drupal.site.sites_subdir}
